---

includePolicies: []
# includePolicies:
#   - require-ro-rootfs
#   - require-run-as-non-root
#   - disallow-privilege-escalation
#   - disallow-privileged-containers
#   - require-drop-all
#   - require-requests-limits

policyRunAsNonRoot:
  validationActions:
    - Audit
  excludedNamespaces: []
  # excludedNamespaces:
  #   - kube-system
  #   - my-legacy-namespace
  excludedLabels:
  # excludedLabels:
  #   exclude-from-policy: "true"
  #   allow-root: "yes"
  # background: false

policyRoRootfs:
  validationActions:
    - Audit
  excludedNamespaces: []
  # excludedNamespaces:
  #   - kube-system
  #   - my-legacy-namespace
  excludedLabels:
  # excludedLabels:
  #   exclude-from-policy: "true"
  #   allow-root: "yes"
  # background: false

policyDropAll:
  validationActions:
    - Audit
  excludedNamespaces: []
  # excludedNamespaces:
  #   - kube-system
  #   - my-legacy-namespace
  excludedLabels:
  # excludedLabels:
  #   exclude-from-policy: "true"
  #   allow-root: "yes"
  # background: false

policyPrivilegeEscalation:
  validationActions:
    - Audit
  excludedNamespaces: []
  # excludedNamespaces:
  #   - kube-system
  #   - my-legacy-namespace
  excludedLabels:
  # excludedLabels:
  #   exclude-from-policy: "true"
  #   allow-root: "yes"
  # background: false

policyPrivilegedContainers:
  validationActions:
    - Audit
  excludedNamespaces: []
  # excludedNamespaces:
  #   - kube-system
  #   - my-legacy-namespace
  excludedLabels:
  # excludedLabels:
  #   exclude-from-policy: "true"
  #   allow-root: "yes"
  # background: false

policyRequestsLimits:
  validationActions:
    - Audit
  excludedNamespaces: []
  # excludedNamespaces:
  #   - kube-system
  #   - my-legacy-namespace
  excludedLabels:
  # excludedLabels:
  #   exclude-from-policy: "true"
  #   allow-root: "yes"
  # background: false
