{{- if has "disallow-privileged-containers" .Values.includePolicies }}
---
apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: disallow-privileged-containers
  annotations:
    policies.kyverno.io/title: Disallow Privileged Containers
    policies.kyverno.io/category: Pod Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.18.0
spec:
  validationActions:
    {{- range (.Values.policyPrivilegedContainers.validationActions) }}
    - {{ . }}
    {{- end }}
  evaluation:
    background:
      enabled: {{ if hasKey .Values.policyPrivilegedContainers "background" }}{{ .Values.policyPrivilegedContainers.background }}{{ else }}true{{ end }}
  matchConstraints:
    resourceRules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
    {{- if .Values.policyPrivilegedContainers.excludedNamespaces }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            {{- toYaml .Values.policyPrivilegedContainers.excludedNamespaces | nindent 12 }}
    {{- end }}
    {{- if .Values.policyPrivilegedContainers.excludedLabels }}
    objectSelector:
      matchExpressions:
      {{- range $key, $val := .Values.policyPrivilegedContainers.excludedLabels }}
        - key: {{ $key }}
          operator: NotIn
          values:
            - {{ $val | quote }}
      {{- end }}
    {{- end }}
  validations:
    - expression: >-
        object.spec.containers.all(c,
          !has(c.securityContext) ||
          !has(c.securityContext.privileged) ||
          c.securityContext.privileged != true
        )
      message: "Privileged containers are not allowed."
{{- end }}
