{{- if has "disallow-privilege-escalation" .Values.includePolicies }}
---
apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: disallow-privilege-escalation
  annotations:
    policies.kyverno.io/title: Disallow Privilege Escalation
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.18.0
spec:
  validationActions:
    {{- range (.Values.policyPrivilegeEscalation.validationActions) }}
    - {{ . }}
    {{- end }}
  evaluation:
    background:
      enabled: true
  matchConstraints:
    resourceRules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
    {{- if .Values.policyPrivilegeEscalation.excludedNamespaces }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            {{- toYaml .Values.policyPrivilegeEscalation.excludedNamespaces | nindent 12 }}
    {{- end }}
    {{- if .Values.policyPrivilegeEscalation.excludedLabels }}
    objectSelector:
      matchExpressions:
      {{- range $key, $val := .Values.policyPrivilegeEscalation.excludedLabels }}
        - key: {{ $key }}
          operator: NotIn
          values:
            - {{ $val | quote }}
      {{- end }}
    {{- end }}
  validations:
    - expression: >-
        object.spec.containers.all(c,
          has(c.securityContext) &&
          has(c.securityContext.allowPrivilegeEscalation) &&
          c.securityContext.allowPrivilegeEscalation == false
        )
      message: "All containers must set allowPrivilegeEscalation to false."
{{- end }}
