{{- if has "require-drop-all" .Values.includePolicies }}
---
apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: require-drop-all
  annotations:
    policies.kyverno.io/title: Require Drop All Capabilities
    policies.kyverno.io/category: Pod Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.18.0
spec:
  validationActions:
    {{- range (.Values.policyDropAll.validationActions) }}
    - {{ . }}
    {{- end }}
  evaluation:
    background:
      enabled: true
  matchConstraints:
    resourceRules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
    {{- if .Values.policyDropAll.excludedNamespaces }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            {{- toYaml .Values.policyDropAll.excludedNamespaces | nindent 12 }}
    {{- end }}
    {{- if .Values.policyDropAll.excludedLabels }}
    objectSelector:
      matchExpressions:
      {{- range $key, $val := .Values.policyDropAll.excludedLabels }}
        - key: {{ $key }}
          operator: NotIn
          values:
            - {{ $val | quote }}
      {{- end }}
    {{- end }}
  validations:
    - expression: >-
        object.spec.containers.all(c,
          has(c.securityContext) &&
          has(c.securityContext.capabilities) &&
          has(c.securityContext.capabilities.drop) &&
          "ALL" in c.securityContext.capabilities.drop
        )
      message: "All containers must drop all Linux capabilities."
{{- end }}
